.\" Manpage/homepage for paste.
.\" See `man 7 groff_man` for more documentation information
.TH paste 1 "$DATE" "paste $VERSION" "paste"
.SH NAME
paste \- pastebin service inspired by ix.io and 0x0.st
.\" .SH SYNOPSIS
.SH DESCRIPTION
.\" Use HTTP POST to upload text to this site.
This site is a work in progress. Currently, no functionality is implemented.
.\" .SH EXAMPLES
.SH AUTHOR
James Box (james@jbox.dev)
.SH SEE ALSO

The public repository for paste is at
.UR $REPOSITORY
.UE .

Inspiration: http://ix.io, https://0x0.st